name: CI

on:
  push:
    branches: [ feature/pytest ]
  pull_request:
    branches: [feature/pytest]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: 
        python -m pip install --upgrade
        pip install pytest
        pip install -r requirements.txt

    - name: Run pytest
      run: pytest
