name: CI

on:
  push:
    branches: [ feature/pytest ]
  pull_request:
    branches: [feature/pytest]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: 
        pip install --upgrade
        pip install pytest
        pip install pytest pytest-cov
        pip install -r requirements.txt

    - name: Run pytest
      run: pytest

    - name: Run tests with coverage
      run: 
        pytest --cov=tests/
        coverage-badge -o coverage.svg

    - name: Extract Coverage Badge URL
      id: extract-badge-url
      run: |
        grep -oP "(?<=\[!\[Coverage\]\().*?(?=\))" coverage.svg > badge_url.txt

    - name: Display Badge URL
      run: cat badge_url.txt

    - name: Update README.md with Coverage Badge
      run: |
        badge_url=$(cat badge_url.txt)
        echo "[![Coverage]($badge_url)]($badge_url)" >> README.md
